name: CI pipeline

on:
#     push:
#         branches: [ "main" ]
# #         pull requestnel a developert kell majd beloni
#     pull_request:
#         branches: [ "main" ]
# #    Allows you to run this workflow manually from the actions tab
    workflow_dispatch:

jobs:
    format_and_lint:
        name: Format and Lint
        
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout branch
                uses: actions/checkout@v3
                with:
                    # Full git history is needed to get a proper
                    # list of changed files within `super-linter`
                    fetch-depth: 0
                    
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
                    
            -   name: Format (java)
                run: mvn process-resources --file pom.xml

            -   name: Lint (java)
                uses: github/super-linter@v4
                env:
                    VALIDATE_ALL_CODEBASE: false
                    VALIDATE_GOOGLE_JAVA_FORMAT: true
                    DEFAULT_BRANCH: main
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build:
        name: Build
        
        runs-on: ubuntu-latest
        
        needs: [format_and_lint]

        steps:
            -   name: Checkout branch
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
                    
            -   name: Maven package
                run: mvn package --file pom.xml
