---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
    #    push:
    #        branches-ignore: [master, main]
    #        # Remove the line above to run when pushing to master
    #    pull_request:
    #        branches: [master, main]
    push:

###############
# Set the Job #
###############
jobs:
    build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

        ##################
        # Load all steps #
        ##################
        steps:
            ##########################
            # Checkout the code base #
            ##########################
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    # Full git history is needed to get a proper
                    # list of changed files within `super-linter`
                    fetch-depth: 0
            # super-linter is buggy on Java code, thats why we lint Java separately
            -   name: Lint Java
                uses: axel-op/googlejavaformat-action@v3
                with:
                    skip-commit: true
            -   name: Print diffs
                run: git --no-pager diff --exit-code

            ################################
            # Run Linter against code base #
            ################################
            -   name: Lint other
                uses: github/super-linter/slim@v4
                env:
                    VALIDATE_ALL_CODEBASE: true
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    VALIDATE_GOOGLE_JAVA_FORMAT: true
                    VALIDATE_YAML: true
