name: CI/CD pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    format:
        name: Format the codebase
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    # Full git history is needed to get a proper
                    # list of changed files within `super-linter`
                    fetch-depth: 0
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
            -   name: Process-resources
                run: mvn -B package --file pom.xml
    lint:
        name: Lint codebase
        runs-on: ubuntu-latest

        steps:
            -   name: Lint Java
                uses: github/super-linter@v4
                env:
                    VALIDATE_ALL_CODEBASE: false
                    VALIDATE_GOOGLE_JAVA_FORMAT: true
                    DEFAULT_BRANCH: main
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build:
        name: Build the artifact

        runs-on: ubuntu-latest

        steps:
            -   name: Maven package
                run: mvn -B package --file pom.xml


